import { useEffect, useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import { Button, Card, ConfigProvider, Descriptions, Divider, Empty, Form, Input, Layout, List, Menu, Modal, Select, Space, Statistic, Switch, Table, Tag, Typography, message } from "antd";
import { AppstoreOutlined, DashboardOutlined, FilterOutlined, PlayCircleOutlined, PlusOutlined, ReloadOutlined, SettingOutlined } from "@ant-design/icons";
import "antd/dist/reset.css";

const { Sider, Content } = Layout;
type Workflow = { id: string; name: string; description?: string; status: string; workspaceId?: string };
type Run = { id: string; status: string; workflowVersionId?: string; inputRef?: string; createdAt?: number };
type Page = "overview" | "workflows" | "runs" | "settings";
async function api<T>(url: string, options?: RequestInit): Promise<T> { const response = await fetch(url, options); const body = await response.json(); if (!response.ok) throw new Error(body.message || "请求失败"); return body; }
const statusColor: Record<string, string> = { active: "green", succeeded: "green", completed: "green", running: "blue", queued: "gold", failed: "red", cancelled: "default" };
const statusLabel: Record<string, string> = { active: "已启用", succeeded: "成功", completed: "已完成", running: "运行中", queued: "排队中", failed: "失败", cancelled: "已取消" };
function StatusTag({ status }: { status: string }) { return <Tag color={statusColor[status] || "default"}>{statusLabel[status] || status}</Tag>; }
function formatDate(value?: number) { return value ? new Date(value).toLocaleString("zh-CN", { dateStyle: "medium", timeStyle: "short" }) : "—"; }

export default function App() {
  const [page, setPage] = useState<Page>("overview"); const [workflows, setWorkflows] = useState<Workflow[]>([]); const [runs, setRuns] = useState<Run[]>([]); const [loading, setLoading] = useState(false); const [open, setOpen] = useState(false); const [selectedRun, setSelectedRun] = useState<Run | null>(null); const [form] = Form.useForm(); const [messageApi, contextHolder] = message.useMessage();
  const load = async () => { setLoading(true); try { const [workflowBody, runBody] = await Promise.all([api<{ items: Workflow[] }>("/api/workflows?limit=100&offset=0"), api<{ items: Run[] }>("/api/runs?limit=100&offset=0")]); setWorkflows(workflowBody.items); setRuns(runBody.items); } catch (error) { messageApi.error(error instanceof Error ? error.message : "加载失败"); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const create = async (values: { name: string; description?: string }) => { try { await api("/api/workflows", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(values) }); messageApi.success("工作流已创建"); setOpen(false); form.resetFields(); void load(); } catch (error) { messageApi.error(error instanceof Error ? error.message : "创建失败"); } };
  const run = async (workflow: Workflow) => { const raw = window.prompt("输入 JSON（留空为 null）", "{}"); if (raw === null) return; try { const input = raw.trim() ? JSON.parse(raw) : null; await api(`/api/workflows/${encodeURIComponent(workflow.id)}/runs`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ input }) }); messageApi.success("已加入运行队列"); void load(); } catch (error) { messageApi.error(error instanceof Error ? error.message : "运行失败"); } };
  const title = { overview: "欢迎回来", workflows: "工作流", runs: "运行记录", settings: "设置" }[page];
  return <ConfigProvider theme={{ token: { colorPrimary: "#1677ff", borderRadius: 12, fontFamily: "-apple-system,BlinkMacSystemFont,'SF Pro Display','Helvetica Neue',sans-serif" } }}>{contextHolder}<Layout className="orchard-layout"><Sider theme="light" breakpoint="lg" collapsedWidth="72" className="orchard-sider"><div className="orchard-brand"><span>✦</span><b>Orchard</b></div><Typography.Text type="secondary" className="menu-caption">WORKSPACE</Typography.Text><Menu mode="inline" selectedKeys={[page]} onClick={({ key }) => setPage(key as Page)} items={[{ key: "overview", icon: <DashboardOutlined />, label: "总览" }, { key: "workflows", icon: <AppstoreOutlined />, label: "工作流" }, { key: "runs", icon: <PlayCircleOutlined />, label: "运行记录" }, { key: "settings", icon: <SettingOutlined />, label: "设置" }]} /><div className="sider-status"><i />本地服务运行中</div></Sider><Content className="orchard-content"><div className="content-header"><div><Typography.Text type="secondary">PERSONAL AI WORKSPACE</Typography.Text><Typography.Title level={2}>{title}</Typography.Title></div><Button icon={<ReloadOutlined />} onClick={() => void load()} loading={loading}>刷新</Button></div>{page === "overview" && <Overview workflows={workflows} runs={runs} loading={loading} onCreate={() => setOpen(true)} onRun={run} onOpen={setPage} />}{page === "workflows" && <WorkflowPage workflows={workflows} loading={loading} onCreate={() => setOpen(true)} onRun={run} />}{page === "runs" && <RunsPage runs={runs} loading={loading} onOpen={setSelectedRun} />}{page === "settings" && <SettingsPage messageApi={messageApi} />}</Content><Modal title="新建工作流" open={open} onCancel={() => setOpen(false)} footer={null}><Form form={form} layout="vertical" onFinish={create}><Form.Item name="name" label="名称" rules={[{ required: true, message: "请输入名称" }]}><Input placeholder="例如：每周报告" maxLength={200} /></Form.Item><Form.Item name="description" label="描述"><Input.TextArea placeholder="这个工作流要完成什么？" maxLength={2000} /></Form.Item><Button type="primary" htmlType="submit" block>创建工作流</Button></Form></Modal><Modal title="运行详情" open={Boolean(selectedRun)} onCancel={() => setSelectedRun(null)} footer={<Button onClick={() => setSelectedRun(null)}>关闭</Button>}>{selectedRun && <Descriptions column={1} bordered size="small"><Descriptions.Item label="运行 ID">{selectedRun.id}</Descriptions.Item><Descriptions.Item label="状态"><StatusTag status={selectedRun.status} /></Descriptions.Item><Descriptions.Item label="工作流版本">{selectedRun.workflowVersionId || "—"}</Descriptions.Item><Descriptions.Item label="创建时间">{formatDate(selectedRun.createdAt)}</Descriptions.Item><Descriptions.Item label="输入引用">{selectedRun.inputRef || "—"}</Descriptions.Item></Descriptions>}</Modal></Layout></ConfigProvider>;
}
function Overview({ workflows, runs, loading, onCreate, onRun, onOpen }: { workflows: Workflow[]; runs: Run[]; loading: boolean; onCreate: () => void; onRun: (workflow: Workflow) => void; onOpen: (page: Page) => void }) { return <><Card className="welcome-card" bordered={false}><Typography.Text>ORCHARD WORKBENCH</Typography.Text><Typography.Title>把想法，变成<br /><span>可执行的流程。</span></Typography.Title><Typography.Paragraph>在一个安静、专注的空间里管理你的 AI 工作流。</Typography.Paragraph></Card><div className="stat-grid"><Card><Statistic title="工作流" value={workflows.length} suffix={<small>已创建</small>} /></Card><Card><Statistic title="近期运行" value={runs.length} suffix={<small>最近记录</small>} /></Card><Card><Statistic title="服务状态" value="正常" valueStyle={{ color: "#34a853" }} suffix={<small>仅本机可用</small>} /></Card></div><Card title={<SectionTitle eyebrow="YOUR AUTOMATIONS" title="工作流" />} extra={<Space><Button type="link" onClick={() => onOpen("workflows")}>查看全部</Button><Button type="primary" icon={<PlusOutlined />} onClick={onCreate}>新建工作流</Button></Space>} className="section-card"><WorkflowList workflows={workflows.slice(0, 5)} loading={loading} onRun={onRun} /></Card><Card title={<SectionTitle eyebrow="ACTIVITY" title="最近运行" />} extra={<Button type="link" onClick={() => onOpen("runs")}>查看全部</Button>} className="section-card"><RunList runs={runs.slice(0, 5)} loading={loading} onOpen={() => undefined} /></Card></> }
function WorkflowList({ workflows, loading, onRun }: { workflows: Workflow[]; loading: boolean; onRun: (workflow: Workflow) => void }) { return <List loading={loading} locale={{ emptyText: <Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="还没有工作流，创建第一个吧。" /> }} dataSource={workflows} renderItem={(workflow) => <List.Item actions={[<StatusTag key="status" status={workflow.status} />, <Button key="run" size="small" disabled={workflow.status !== "active"} onClick={() => onRun(workflow)}>运行</Button>]}><List.Item.Meta title={workflow.name} description={workflow.description || "暂无描述"} /></List.Item>} /> }
function WorkflowPage({ workflows, loading, onCreate, onRun }: { workflows: Workflow[]; loading: boolean; onCreate: () => void; onRun: (workflow: Workflow) => void }) { const [query, setQuery] = useState(""); const filtered = useMemo(() => workflows.filter((item) => `${item.name} ${item.description || ""}`.toLowerCase().includes(query.toLowerCase())), [workflows, query]); return <Card className="section-card page-card" title={<SectionTitle eyebrow="YOUR AUTOMATIONS" title={`${workflows.length} 个工作流`} />} extra={<Button type="primary" icon={<PlusOutlined />} onClick={onCreate}>新建工作流</Button>}><div className="toolbar"><Input allowClear prefix={<FilterOutlined />} placeholder="搜索工作流" value={query} onChange={(event) => setQuery(event.target.value)} /></div><WorkflowList workflows={filtered} loading={loading} onRun={onRun} /></Card> }
function RunList({ runs, loading, onOpen }: { runs: Run[]; loading: boolean; onOpen: (run: Run) => void }) { return <List loading={loading} locale={{ emptyText: <Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="暂无运行记录" /> }} dataSource={runs} renderItem={(item) => <List.Item className="run-item" onClick={() => onOpen(item)}><div><Typography.Text strong>{item.id}</Typography.Text><Typography.Text type="secondary" className="run-time">{formatDate(item.createdAt)}</Typography.Text></div><StatusTag status={item.status} /></List.Item>} /> }
function RunsPage({ runs, loading, onOpen }: { runs: Run[]; loading: boolean; onOpen: (run: Run) => void }) { return <Card className="section-card page-card" title={<SectionTitle eyebrow="ACTIVITY" title={`${runs.length} 条运行记录`} />}><Table rowKey="id" loading={loading} dataSource={runs} locale={{ emptyText: <Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="暂无运行记录" /> }} onRow={(record) => ({ onClick: () => onOpen(record), style: { cursor: "pointer" } })} columns={[{ title: "运行 ID", dataIndex: "id", ellipsis: true }, { title: "状态", dataIndex: "status", render: (status: string) => <StatusTag status={status} /> }, { title: "工作流版本", dataIndex: "workflowVersionId", ellipsis: true, responsive: ["md"] }, { title: "创建时间", dataIndex: "createdAt", render: (value?: number) => formatDate(value) }]} /></Card> }
function SettingsPage({ messageApi }: { messageApi: { success: (content: string) => void } }) { const [saved, setSaved] = useState(() => localStorage.getItem("orchard.settings") === "saved"); const save = () => { localStorage.setItem("orchard.settings", "saved"); setSaved(true); messageApi.success("设置已保存到本机"); }; return <div className="settings-grid"><Card className="section-card" title={<SectionTitle eyebrow="WORKSPACE" title="工作区设置" />}><Form layout="vertical"><Form.Item label="工作区名称"><Input defaultValue="我的 Orchard 工作区" /></Form.Item><Form.Item label="默认时区"><Select defaultValue="Asia/Shanghai" options={[{ value: "Asia/Shanghai", label: "中国标准时间（Asia/Shanghai）" }, { value: "UTC", label: "协调世界时（UTC）" }]} /></Form.Item><Form.Item label="运行完成后保留记录"><Select defaultValue="forever" options={[{ value: "forever", label: "永久保留" }, { value: "90", label: "保留 90 天" }, { value: "30", label: "保留 30 天" }]} /></Form.Item><Button type="primary" onClick={save}>{saved ? "已保存" : "保存设置"}</Button></Form></Card><Card className="section-card" title={<SectionTitle eyebrow="RUNTIME" title="运行服务" />}><div className="setting-row"><div><Typography.Text strong>本地运行服务</Typography.Text><Typography.Paragraph type="secondary">工作流仅在当前设备运行和存储。</Typography.Paragraph></div><Switch defaultChecked /></div><Divider /><div className="setting-row"><div><Typography.Text strong>并发运行数</Typography.Text><Typography.Paragraph type="secondary">同时执行的工作流数量。</Typography.Paragraph></div><Select defaultValue="2" style={{ width: 92 }} options={["1", "2", "4", "8"].map((value) => ({ value, label: value }))} /></div><Divider /><Typography.Text type="secondary">版本 0.1.0 · Orchard Workbench</Typography.Text></Card></div> }
function SectionTitle({ eyebrow, title }: { eyebrow: string; title: string }) { return <div><Typography.Text type="secondary">{eyebrow}</Typography.Text><Typography.Title level={4}>{title}</Typography.Title></div>; }
const root = document.getElementById("root"); if (!root) throw new Error("Workbench root element is missing"); createRoot(root).render(<App />);
